### PR TITLE
Increase player number for team color and glow.

### PR DESCRIPTION
**Pull request by Ralle**
Allows for the Reforged team colors and glows to work.

### CODE REVIEW

**Comment by flowtsohg** [comment]
I actually had it set up for Reforged, but the API didn't have the new textures so the console would get error spam.

The number should be 28, no? 24 players, and the 4 neutrals.

Either way, since the team colors for TFT and Reforged are split now, it would be more correct to run the loop with the matching number for each, e.g. by using the `reforged` local boolean.

**Comment by Ralle** [comment]
That’s true of course. But this code edit works and all the colours exist. I guess it makes sense to only load what’s expected from the Boolean to save bandwidth.

**Comment by flowtsohg** [comment]
I care less about bandwidth and more about the logic here, so bare with me.

The TFT and Reforged render paths use separate arrays of textures for team colors/glows, because, well, they are literally different textures (and last time I checked in the beta, the new glows were horribly pixelated as well, didn't you open an issue for this?)

At the same time, it's probably annoying to have to handle these details on the client. How much of a chore would it be to dynamically change the UI using `model.reforged`?
It also somewhat constrains the client, who even said you don't want to simply show all possible colors for all models regardless of the model's own version.

I don't really have a question, but rather want to hear what you have to say on the matter, since it affects you.

**Comment by Ralle** [comment]
On Wed, Dec 30, 2020, at 17:41, Chananya Freiman wrote:
> 

> I care less about bandwidth and more about the logic here, so bare with me.

> The TFT and Reforged render paths use separate arrays of textures for team colors/glows, because, well, they are literally different textures (and last time I checked in the beta, the new glows were horribly pixelated as well, didn't you open an issue for this?)


I didn't see this for myself. Curious.


> At the same time, it's probably annoying to have to handle these details on the client. How much of a chore would it be to dynamically change the UI using `model.reforged`?
> It also somewhat constrains the client, who even said you don't want to simply show all possible colors for all models regardless of the model's own version.

> I don't really have a question, but rather want to hear what you have to say on the matter, since it affects you.


I have a feeling that I am not well enough informed to answer this. Wouldn't the user of the library just know not to ask for team colors >14 or is it more complex than that because the viewer preloads them and we wouldn't want 10 404s because someone is using the viewer with TFT instead of Reforged?

**Comment by flowtsohg** [comment]
The viewer does preload them. In the long long past it loaded them just when actually changing to a new team color, which meant there would be a delay before it's shown.

It's not even just the 404 spam, but I wonder what is the logical thing to do here.
What really if you want to use team color 20 on a TFT model to see how it would look? currently there is no way to do this (regardless if you change the loop or not), and I am not sure whether there should be a way, or how such a way would look, considering they are literally two separate group of textures.

For example the easiest thing I can think of is to be able to set the team color mode per-model (or per-instance?), regardless of whether it's TFT or Reforged, and e.g. default to whatever the model actually is, or have some per-handler default.
But is there something nicer?

**Comment by Ralle** [comment]
You can use classic models in Reforged. And in Reforged there is no distinct place for non-HD team colors. So if it was me, I would simply allow setting the team color to whatever loaded succesfully.

**Comment by flowtsohg** [comment]
Suppose the code first tries to get a Reforged team color first to see if it exists, and then loads whatever does exist.
Now if you have a TFT model, it will show up with Reforged textures.
Maybe this doesn't even matter and I am making a big deal out of nothing 🤔

**Comment by flowtsohg** [comment]
Sorry to ruin your PR, but this was just an old issue I never got to solving.
Not the Reforged thing, but models loading the team textures because I didn't want to force passing a path solver in some way at setup.
Check the new version with something like
```ts
viewer.addHandler(mdxHandler, wc3PathSolver, true)
```
to set it for Reforged teams.

**Comment by Ralle** [comment]
Works great!

**Pull request closed without merging**
